apiVersion: v1
kind: Service
metadata:
  name: deel-test-service
spec:
  selector:
    app: deel-test
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
