apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress-cluster-role
subjects:
- kind: ServiceAccount
  name: nginx-ingress-service-account
  namespace: ingress-nginx
