# Default values for deel-test.
# This is a YAML-formatted file.
# values
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: 891377174375.dkr.ecr.us-east-1.amazonaws.com/deel-test-registry
<<<<<<< HEAD
  tag: 7c50859
=======
<<<<<<< HEAD
  tag: e67979d
=======
  tag: e67979d
>>>>>>> 77cbf3aa6ebbcf9ca40920c4ecc554474d787c15
>>>>>>> f28d3fb08385dbecc1ff7d9a416d186960e469ad
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort:
    port: 80

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 10

container:
  name: deel-test
  port: 80
