# Default values for deel-test.
# This is a YAML-formatted file.
# values
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: 975050026662.dkr.ecr.eu-west-1.amazonaws.com/deel-test-registry
  tag: 57eac75

  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80 # Corrected: Removed the 'port' field inside 'targetPort'

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

strategy:
  type: RollingUpdate
  maxUnavailable: 1
  maxSurge: 10

container:
  name: deel-test
  port: 80 # Moved the container port specification here if needed
